# Generated by Django 5.1.4 on 2024-12-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_appointments_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='service',
            field=models.CharField(default='Hello', max_length=50),
            preserve_default=False,
        ),
    ]
