# Generated by Django 5.1.4 on 2024-12-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20231222_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('salon_material', 'Salon Material'), ('supplies', 'Supplies'), ('other_purchases', 'Other Purchases'), ('marketing', 'Marketing'), ('commissions', 'Commissions'), ('salaries', 'Salaries'), ('rent', 'Rent'), ('electricity', 'Electricity'), ('other_utilities', 'Other Utilities'), ('tele_internet', 'Telephone & Internet'), ('legal', 'Legal & Professional'), ('cleaning', 'Cleaning'), ('others', 'Others')], default='others', max_length=50),
        ),
    ]
