# Generated by Django 5.1.4 on 2024-12-21 22:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_expense_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomestatement',
            options={'ordering': ['-period']},
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='period',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
    ]
